# Generated by Django 5.0.3 on 2024-03-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='date_added',
        ),
    ]
