# Generated by Django 5.0.3 on 2024-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='isrented',
            field=models.BooleanField(default=True),
        ),
    ]
