# Generated by Django 5.0.3 on 2024-03-23 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart_item_isrented'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('phone', models.CharField(max_length=10)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_orders', 'Can view orders'), ('can_view_users', 'Can view users'), ('can_view_userprofile', 'Can view user profile'), ('can_view_movies', 'Can view movies'), ('can_edit_moviequantity', 'Can view movie quantity')],
            },
        ),
    ]
