# Generated by Django 5.0.3 on 2024-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_movie_movie_quantity_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_view_orders', 'Can view orders'), ('can_view_users', 'Can view users'), ('can_view_userprofile', 'Can view user profile'), ('can_view_movies', 'Can view movies'), ('can_edit_moviequantity', 'Can edit movie quantity')]},
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='movies',
            field=models.ManyToManyField(to='home.movie'),
        ),
    ]
