# Generated by Django 5.0.3 on 2024-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_order_isrented_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isrented',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
