# Generated by Django 5.0.3 on 2024-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_movie_movie_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_available_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
