# Generated by Django 5.0.3 on 2024-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_movie_available_quantity_movie_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certification',
            field=models.CharField(choices=[('U', 'U'), ('U/A', 'U/A'), ('A', 'A')], default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
