# Generated by Django 5.0.3 on 2024-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_order_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Returned', 'Not Returned'), ('Sold', 'Sold'), ('Overdue', 'Overdue'), ('Returned', 'Returned')], default='Not Returned', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
