# Generated by Django 5.0.3 on 2024-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_userprofile_dob_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
